version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - gems_volume:/gems:cached
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/var/lib/redis/data:cached

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "bundle check || bundle install &&
               bundle exec sidekiq"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:cached
      - gems_volume:/gems:cached
    env_file: .env

volumes:
  gems_volume:
  db_volume:
  redis_volume:
